version: '3.8'
services:
  web:
    image: wakeonlan
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: WAKE
      DB_PASSWORD: WAKE
      DB_NAME: WAKE
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: WAKE
      MYSQL_USER: WAKE
      MYSQL_PASSWORD: WAKE
      MYSQL_DATABASE: WAKE
    ports:
      - "3306:3306"
    volumes:
      - /mnt/docker:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
